first pass code changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,6 @@ name: Main
 on:
   push:
     branches:
-      - master
       - main
     tags:
       - v*
@@ -13,63 +12,41 @@ jobs:
 
   main:
     name: Main Process
-    runs-on: ubuntu-latest
-    env:
-      GO_VERSION: 1.17
-      GOLANGCI_LINT_VERSION: v1.42.1
-      YAEGI_VERSION: v0.14.2
-      CGO_ENABLED: 0
-    defaults:
-      run:
-        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
-
+    runs-on: ubuntu-24.04
     steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
 
-      # https://github.com/marketplace/actions/setup-go-environment
-      - name: Set up Go ${{ env.GO_VERSION }}
-        uses: actions/setup-go@v2
+      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
         with:
-          go-version: ${{ env.GO_VERSION }}
+          go-version: '>=1.24.0'
 
-      # https://github.com/marketplace/actions/checkout
-      - name: Check out code
-        uses: actions/checkout@v2
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7
         with:
-          path: go/src/github.com/${{ github.repository }}
-          fetch-depth: 0
-
-      # https://github.com/marketplace/actions/cache
-      - name: Cache Go modules
-        uses: actions/cache@v2
-        with:
-          path: ${{ github.workspace }}/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
-
-      # https://golangci-lint.run/usage/install#other-ci
-      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
-        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}
-
-      - name: Install Yaegi ${{ env.YAEGI_VERSION }}
-        run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}
-
-      - name: Setup GOPATH
-        run: go env -w GOPATH=${{ github.workspace }}/go
+          version: latest
 
       - name: Check and get dependencies
         run: |
           go mod tidy
           git diff --exit-code go.mod
-          # git diff --exit-code go.sum
           go mod download
           go mod vendor
-          # git diff --exit-code ./vendor/
 
-      - name: Lint and Tests
-        run: make
+      - name: go mod tidy
+        run: |
+          go mod tidy
+          if ! git diff --exit-code go.mod go.sum; then
+            echo "Error: go.mod or go.sum is not tidy. Run 'go mod tidy' locally and commit the changes."
+            exit 1
+          fi
 
-      - name: Run tests with Yaegi
-        run: make yaegi_test
-        env:
-          GOPATH: ${{ github.workspace }}/go
+      - name: go mod vendor
+        run: |
+          go mod vendor
+          if ! git diff --exit-code vendor/; then
+            echo "Error: vendor/ directory is not up-to-date. Run 'go mod vendor' locally and commit the changes."
+            exit 1
+          fi
+
+      - name: unit test
+        run: go test -v -race .
